apiVersion: v1
kind: Service
metadata:
  name: micrometer-stackdriver-demo-svc
  labels:
    app: micrometer-stackdriver-demo
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: micrometer-stackdriver-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micrometer-stackdriver-demo
spec:
  selector:
    matchLabels:
      app: micrometer-stackdriver-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: micrometer-stackdriver-demo
    spec:
      containers:
      - name: micrometer-stackdriver-demo
        image: gcr.io/micrometer-stackdriver/micrometer-stackdriver-demo
        ports:
        - containerPort: 8080
          name: server