apiVersion: apps/v1
kind: Deployment
metadata:
  name: micrometer-stackdriver-demo
spec:
  selector:
    matchLabels:
      app: micrometer-stackdriver-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: micrometer-stackdriver-demo
      annotations:
          prometheus.io/scrape: 'true'
          prometheus.io/path: '/actuator/prometheus'
    spec:
      containers:
      - name: micrometer-stackdriver-demo
        image: gcr.io/micrometer-stackdriver/micrometer-stackdriver-demo
        ports:
        - containerPort: 8080
          name: server
