apiVersion: v1
kind: Service
metadata:
  name: micrometer-stackdriver-demo-svc
  labels:
    app: micrometer-stackdriver-demo
spec:
  type: LoadBalancer
  loadBalancerIP: 104.154.156.250
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: micrometer-stackdriver-demo
